### ISSUE TITLE
`docker-compose up` not working for me.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#30]
- Once I had Docker running, `./build_docker_container.py` worked fine.
- Maybe it should automatically `mkdir ~/context`... but it's possible someone might already have a directory there, and be using it for something else?
- `docker-compose up` fails with `Cannot locate specified Dockerfile: Dockerfile`

```
hubmap-data-portal$ ./build_docker_container.py 
Writing Git revision v0.1-33-gb2a9414 to hubmap/frontend/src/git-version.json
Running "docker build -q -t hubmap/data-portal-python-base:20190719-140727 -f docker/base/uwsgi+python-env/Dockerfile ."
Tagged image sha256:8246b827f62d32d569f98b152d74896e4842ed6991cb19317634f0a66db4b14b as hubmap/data-portal-python-base:20190719-140727
Running "docker build -q -t hubmap/data-portal-reactjs-base:20190719-140727 -f docker/base/reactjs_app/Dockerfile ."
Tagged image sha256:4c81ccdb6eefe74e8949d211af01c15e6e3af80c9f0c0cd9e682d7601130acb1 as hubmap/data-portal-reactjs-base:20190719-140727
Running "docker build -q -t hubmap/data-portal-python-dev:20190719-140727 -f docker/dev/uwsgi+python-env/Dockerfile ."
Tagged image sha256:e0e6fcebd3ae60b3abb69eb3eb6c9c46096b8f24ecb54c0a88743c3ff2ac20f2 as hubmap/data-portal-python-dev:20190719-140727
Running "docker build -q -t hubmap/data-portal-reactjs-dev:20190719-140727 -f docker/dev/reactjs_app/Dockerfile ."
Tagged image sha256:d5ede68698d89cf042ee63efdeaf45b601d64f1de67ceaa908c54d7d07f8b6df as hubmap/data-portal-reactjs-dev:20190719-140727

hubmap-data-portal$ cd docker/

docker$ docker-compose up
ERROR: build path /Users/chuck/context either does not exist, is not accessible, or is not a valid URL.

docker$ mkdir /Users/chuck/context

docker$ docker-compose up
Creating network "chuck_default" with the default driver
Pulling redis (redis:3.2.7-alpine)...
3.2.7-alpine: Pulling from library/redis
0a8490d0dfd3: Pull complete
c8d0e817ebe2: Pull complete
7f2a4f935feb: Pull complete
4664c32a79d3: Pull complete
de138f8bbe03: Pull complete
c82352e732c0: Pull complete
Digest: sha256:95f0c9434f37db0a4f9563379184ff4895685d2381e2d81bd10dfcbcadfc095f
Status: Downloaded newer image for redis:3.2.7-alpine
Building web
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by mruffalo** [comment]
Can you try running `docker-compose up` from the `docker/dev` directory?

**Comment by mccalluc** [comment]
yep, that worked. Now I think everything is running:
```
dev$ docker-compose ps
       Name                      Command               State                           Ports                        
--------------------------------------------------------------------------------------------------------------------
dev_django_1          python3 /opt/hubmap-data-p ...   Up      0.0.0.0:8000->8000/tcp                               
dev_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp       
dev_neo4j_1           /sbin/tini -g -- /docker-e ...   Up      7473/tcp, 0.0.0.0:7474->7474/tcp,                    
                                                               0.0.0.0:7687->7687/tcp                               
dev_postgres_1        docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp                               
dev_react_app_1       docker-entrypoint.sh ./npm ...   Up      0.0.0.0:3000->3000/tcp 
```
but there is an error from http://localhost:8000/
```
Request Method: | GET
-- | --
http://localhost:8000/
2.2.3
TemplateDoesNotExist
index.html
/usr/local/lib/python3.6/dist-packages/django/template/loader.py in get_template, line 19
/usr/bin/python3
3.6.8
['/opt/hubmap-data-portal/hubmap',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 19 Jul 2019 22:26:40 +0000
```

**Comment by mccalluc** [comment]
and in the log:
<details>

```
[19/Jul/2019 22:26:33] "GET /api/colors/?format=json HTTP/1.1" 200 399
Internal Server Error: /api/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "dataportal_scrnaseqstudybarcoded" does not exist
LINE 1: ...crnaseqstudybarcoded"."unique_barcode_count" FROM "dataporta...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 466, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/hubmap-data-portal/hubmap/dataportal/views.py", line 31, in get
    response = get_response_for_request(self, request, format)
  File "/opt/hubmap-data-portal/hubmap/dataportal/utils.py", line 47, in get_response_for_request
    chain(scrna_barcorded, scrna_cdna, scrna_atac, microscopy, mass_cytometry, spatial_transcriptomic))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "dataportal_scrnaseqstudybarcoded" does not exist
LINE 1: ...crnaseqstudybarcoded"."unique_barcode_count" FROM "dataporta...
                                                             ^

[19/Jul/2019 22:26:33] "GET /api/?format=json HTTP/1.1" 500 15536
Internal Server Error: /api/genes/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "dataportal_gene" does not exist
LINE 1: ...aportal_gene"."tissue_expression_heatmap_id" FROM "dataporta...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 466, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/hubmap-data-portal/hubmap/dataportal/views.py", line 67, in get
    response = get_genes(self, request)
  File "/opt/hubmap-data-portal/hubmap/dataportal/utils.py", line 148, in get_genes
    print(genes)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "dataportal_gene" does not exist
LINE 1: ...aportal_gene"."tissue_expression_heatmap_id" FROM "dataporta...
                                                             ^

[19/Jul/2019 22:26:33] "GET /api/genes/?format=json HTTP/1.1" 500 15518
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/hubmap-data-portal/hubmap/frontend/views.py", line 49, in get
    return render(request, 'index.html')
  File "/usr/local/lib/python3.6/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
```

</details>
