### ISSUE TITLE
Linting javascript code

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#43]
Linting tools can help catch errors and ensure a consistent style. For javascript, eslint is a good bundle ....

but I have been unable to run it after install: I get this error:
<details>

```
$ eslint src
Error: ESLint configuration in package.json » eslint-config-react-app is invalid:
	- Property "overrides" is the wrong type (expected array but got `{"files":["**/*.ts","**/*.tsx"],"parser":"@typescript-eslint/parser","parserOptions":{"ecmaVersion":2018,"sourceType":"module","ecmaFeatures":{"jsx":true},"warnOnUnsupportedTypeScriptVersion":true},"plugins":["@typescript-eslint"],"rules":{"default-case":"off","no-dupe-class-members":"off","@typescript-eslint/no-angle-bracket-type-assertion":"warn","no-array-constructor":"off","@typescript-eslint/no-array-constructor":"warn","@typescript-eslint/no-namespace":"error","no-unused-vars":"off","@typescript-eslint/no-unused-vars":["warn",{"args":"none","ignoreRestSiblings":true}],"no-useless-constructor":"off","@typescript-eslint/no-useless-constructor":"warn"}}`).

Referenced from: /Users/chuck/github/hubmapconsortium/hubmap-data-portal/hubmap/frontend/package.json
    at validateConfigSchema (/usr/local/lib/node_modules/eslint/lib/shared/config-validator.js:286:15)
    at ConfigArrayFactory._normalizeConfigData (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:469:9)
    at ConfigArrayFactory._loadConfigData (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:414:21)
    at ConfigArrayFactory._loadExtendedShareableConfig (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:714:21)
    at ConfigArrayFactory._loadExtends (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:613:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/usr/local/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
```

</details>

Digging into it:
```bash
# Yes, what is installed does look like an object:
$ grep overrides node_modules/eslint-config-react-app/index.js 
  overrides: {

# What versions are installed?
$ npm list eslint-config-react-app
frontend@0.1.0 /Users/chuck/github/hubmapconsortium/hubmap-data-portal/hubmap/frontend
├── eslint-config-react-app@4.0.1 
└─┬ react-scripts@3.0.1
  └── eslint-config-react-app@4.0.1  deduped

# When we look at the source code for these versions, do we see the same thing?
$ curl --silent https://raw.githubusercontent.com/facebook/create-react-app/v3.0.1/packages/eslint-config-react-app/index.js | grep override
  overrides: {
$ curl --silent https://raw.githubusercontent.com/facebook/create-react-app/v3.0.1/packages/eslint-config-react-app/package.json | head -n3
{
  "name": "eslint-config-react-app",
  "version": "4.0.1",

# What if we look at more recent development?
$ curl --silent https://raw.githubusercontent.com/facebook/create-react-app/master/packages/eslint-config-react-app/index.js | grep override
  overrides: [
$ curl --silent https://raw.githubusercontent.com/facebook/create-react-app/master/packages/eslint-config-react-app/package.json | head -n3
{
  "name": "eslint-config-react-app",
  "version": "4.0.1",
```

So it looks like the latest development on master has changed overrides to an array, but there has not been a release of that change. Maybe this has changed from an array, to an object, and back to an array, or maybe our version of eslint is too far ahead, and the latest versions of the dependencies do not match what it needs?

I've tried installing older eslints, but it didn't help:
```
# last release for each of these major versions...
$ npm install --save-dev eslint@5.16.0
$ npm install --save-dev eslint@4.19.1
```

**Comment by mccalluc** [comment]
Done.
