### ISSUE TITLE
Update container to include oauth2_provider

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#89]
I am trying to get my development environment back up with the latest changes in the `develop` branch. I have updated, and then `docker-compose up`, and http://localhost:3000 is up, but empty. Next, I try `run_migrations_in_container.py`:
<details>

```
hubmap-data-portal$ ./run_migrations_in_container.py 
Running "docker exec d9a059160247 python3 /opt/hubmap-data-portal/hubmap/manage.py migrate --force-color"
Traceback (most recent call last):
  File "/opt/hubmap-data-portal/hubmap/manage.py", line 21, in <module>
    main()
  File "/opt/hubmap-data-portal/hubmap/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oauth2_provider'
Traceback (most recent call last):
  File "./run_migrations_in_container.py", line 92, in <module>
    main(args.pretend)
  File "./run_migrations_in_container.py", line 85, in main
    print_run(docker_migrate_command, pretend)
  File "./run_migrations_in_container.py", line 64, in print_run
    proc = run(command, check=True, **kwargs)
  File "/Users/chuck/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'exec', 'd9a059160247', 'python3', '/opt/hubmap-data-portal/hubmap/manage.py', 'migrate', '--force-color']' returned non-zero exit status 1.
```

</details>

Do I need to update the images before `docker-compose up`? Or something else? My end goal would be a sort sequence of commands in the README which will reliably bring up a clean environment with demo data loaded.

**Comment by mruffalo** [comment]
I built, tagged, and pushed new containers with the updated `requirements.txt` entries -- `docker-compose pull` will download these.

This suggests that we need a way to communicate when there are new containers available/required due to new dependencies; this will likely happen again soon with connectors for additional database engines like MongoDB and Neo4j.

**Comment by mccalluc** [comment]
@mruffalo : I think the communication itself isn't hard: Just send post a notice on Slack. But then we need to get our environments up to date: I've started a script [here](https://github.com/hubmapconsortium/hubmap-data-portal/compare/mccalluc/refresh-dev-environment-script?expand=1) ... Could you fill in the part about initializing the database? Or maybe you see a problem with this approach?

**Comment by mccalluc** [comment]
Original issue resolved. Larger issue (documenting release process) covered by #51.
